<style>
    .label{
        width: 150px;
        float: left;
    }
    .content{
        width: 200px;
        float: left;
    }
    .action{

        float: left;
    }

    p{
        clear: both;
        margin-top: 7px;
    }

    

</style>

<script type="text/javascript">

    function setError(errorMessage) {
        $('#main_message').text(errorMessage).addClass('error');
    }
    function setSuccess(successMessage) {
        $('#main_message').text(successMessage).addClass('success');
    }

    function removeError() {
        $('#message').text('');
        $('.error').removeClass('error');
        $('.success').removeClass('success');
    }

    function ajaxSave(url, postVal, successMessage, btId) {

        $('#' + btId).hide();
        $.post(url, postVal, function(data) {
            var re = null;
            try {
                re = JSON.parse(data);
            }
            catch (e) {
            }

            if (re === null) {
                setError(data);
                return;
            }

            if (typeof re.error_message !== 'undefined') {
                setError(re.error_message);
            }
            else {
                setSuccess(successMessage);
            }

        }).fail(function(data) {
            setError(data);
        }).always(function() {
            $('#' + btId).show();
        });
    }

    $(document).ready(function() {
        $('#email_bt').click(function() {

            removeError();
            var newValue = $('#email').val();
            postVal = {
                email: newValue,
                id:<?= $this->edit_user['id'] ?>,
                action: 'save_email'
            };

            var url = "<?= $this->popUrl('usermng/save') ?>";
            ajaxSave(url, postVal, 'Email 已经被更新', 'email_bt');
        });
        $('#password_bt').click(function() {

            removeError();
            var newValue = $('#password').val();
            postVal = {
                new_password: newValue,
                id:<?= $this->edit_user['id'] ?>,
                action: 'save_password'
            };

            var url = "<?= $this->popUrl('usermng/save') ?>";
            ajaxSave(url, postVal, '新密码已经设置好了', 'password_bt');
        });
        $('#status_bt').click(function() {

            removeError();
            var newValue = $('#status').val();
            postVal = {
                new_status: newValue,
                id:<?= $this->edit_user['id'] ?>,
                action: 'save_status'
            };

            var url = "<?= $this->popUrl('usermng/save') ?>";
            ajaxSave(url, postVal, '用户的状态已经更新', 'status');
        });


    });</script>

<div id="main_message"></div>
<? if ($this->edit_user === false): ?>
    数据错误
<? else: ?>


    <p>
    <div class='label'>
        姓名
    </div>
    <div class='content'>
        <?= htmlspecialchars($this->edit_user['name'], ENT_QUOTES, "UTF-8") ?>
    </div>


    </p>


    <p>

    <div class='label'>
        Email
    </div>
    <div class='content'>
        <input id='email' value='<?= htmlspecialchars($this->edit_user['email'], ENT_QUOTES, "UTF-8") ?>' size="20" type="text"> 


    </div>
    <div class='action'>
        <button id='email_bt'>更改</button>


    </div>

    </p>

    <p>

    <div class='label'>
        新密码
    </div>
    <div class='content'>
        <input id='password' value='' size="20" type="text"> 


    </div>
    <div class='action'>
        <button id='password_bt'>重置密码</button>


    </div>

    </p>

    <p>

    <div class='label'>
        状态
    </div>
    <div class='content'>

        <? if (in_array($this->type_id, $this->classmate_types)): ?>
            <select id="status">
                <? foreach ($this->classmate_types as $one): ?>
                    <option value="<?= $one ?>" <? if ($one === $this->type_id): ?>selected="selected"<? endif; ?>><?= htmlspecialchars($this->types[$one], ENT_QUOTES, "UTF-8") ?></option>
                <? endforeach; ?>
            </select>

        <? elseif (in_array($this->type_id, $this->friend_types)): ?>
            <select id="status">
                <? foreach ($this->friend_types as $one): ?>
                    <option  value="<?= $one ?>" <? if ($one === $this->type_id): ?>selected="selected"<? endif; ?>><?= htmlspecialchars($this->types[$one], ENT_QUOTES, "UTF-8") ?></option>
                <? endforeach; ?>
            </select>

        <? elseif (in_array($this->type_id, $this->admin_types)): ?>
            <?= htmlspecialchars($this->types[$this->type_id], ENT_QUOTES, "UTF-8") ?>
        <? else : ?>
            非法ID: <?= $this->type_id ?>
        <? endif; ?>

    </div>
    <? if (!in_array($this->type_id, $this->admin_types)): ?>
        <div class='action'>
            <button id='status_bt'>设置</button>


        </div>
    <? endif; ?>
    </p>

<? endif; ?>
