<style>
    .error_message: {
        background-color: #b81900;
    }
</style>
<script type="text/javascript">

</script>

<div class="error_message">
    <? foreach ($this->errorMessage as $one): ?>
        <div ><?= $one;?></div>
    <? endforeach; ?>
</div>
<div>
    <form action="/teacher_mng/save" method="post">
        <input name="id" type="hidden" value="<?= $this->id ?>"/>
        <div>


            <select name="type" id="type">
                <? foreach ($this->admin_types as $value => $name): ?>
                    <option value='<?= $value?>' <? if (isset($value) && intval($value) == $this->type): ?>selected="selected"<? endif; ?>><?= $name; ?></option>
                <? endforeach; ?>
            </select>


        </div>


        <div><span>Email:</span><span><?= $this->email ?></span></div>
        <div><label>First Name</label><input type="text" name="first_name" value="<?= $this->first ?>"/></div>
        <div><label>Last Name</label><input type="text" name="last_name" value="<?= $this->last ?>"/></div>

        <div>
            <button type="submit">Save</button>
        </div>
    </form>

</div>
