<style>

</style>
<script type="text/javascript">

</script>


<div>
    <form action="/teacher_mng/create" method="post">
        <div><label>Email</label><input type="text" name="email"/></div>
        <div><label>First Name</label><input type="text" name="first_name"/></div>
        <div><label>Last Name</label><input type="text" name="last_name"/></div>
        <div><label>password</label><input type="password" name="password1"/></div>
        <div><label>password again</label><input type="password" name="password2"/></div>
        <div>
            <button type="submit">Create</button>
        </div>
    </form>

</div>
