<style>
    .error_message: {
        color: #cd0a0a;
    }
</style>

<div class="error_message"><?= $this->errorMessage?></div>
<form action="<?= $this->popUrl('teacher_mng/reset_my_password'); ?>" method="post">
    <div>
        <label>Current Password:</label><input type="password" name="old_password"/>
    </div>

    <div>
        <label>New password:</label><input type="password" name="new_password1"/>
    </div>

    <div>
        <label>New password again:</label><input type="password" name="new_password2"/>
    </div>

    <button type="submit">Reset my password</button>

</form>