<style>
    .error_message: {
        background-color: #b81900;
    }
</style>
<script type="text/javascript">

</script>

<div class="error_message">
    <? foreach ($this->errorMessage as $one): ?>
        <div ><?= $one;?></div>
    <? endforeach; ?>
</div>
<div>
    <h2>Change password for <?= $this->email;?></h2>
    <form action="/teacher_mng/save_password" method="post">
        <input name="id" type="hidden" value="<?= $this->id ?>"/>

        <div><label>password </label><input type="password" name="password1" value=""/></div>
        <div><label>password again</label><input type="password" name="password2" value=""/></div>

        <div>
            <button type="submit">Save</button>
        </div>
    </form>

</div>
