<style>

</style>
<script type="text/javascript" >



    function setError(errorMessage) {
        $('#main_message').text(errorMessage).addClass('error');
    }
    function setSuccess(successMessage) {
        $('#main_message').text(successMessage).addClass('success');
    }

    function removeError() {
        $('#message').text('');
        $('.error').removeClass('error');
        $('.success').removeClass('success');
    }

    function ajaxSave(url, postVal, successMessage, btId, successFun, errorFunc, finalFunction) {

        $('#' + btId).hide();
        $.post(url, postVal, function(data) {
            var re = null;
            try {
                re = JSON.parse(data);
            }
            catch (e) {
            }

            if (re === null) {
                setError(data);
                return;
            }

            if (typeof re.error_message !== 'undefined') {


                if (typeof errorFunc === 'function') {
                    errorFunc();
                }
                if (typeof re.redirect_url !== 'undefined') {
                    alert(re.error_message);
                    window.location = re.redirect;
                }
                else {
                    setError(re.error_message);
                }

            }
            else {

                if (typeof successFun === 'function') {
                    successFun();
                }
                if (typeof re.redirect_url !== 'undefined') {
                    alert(successMessage);
                    window.location = re.redirect;
                }
                else {
                    setSuccess(successMessage);
                }
            }


        }).fail(function(data) {
            setError(data);
            if (typeof errorFunc === 'function') {
                errorFunc();
            }
        }).always(function() {
            $('#' + btId).show();

            if (typeof finalFunction === 'function') {
                finalFunction();
            }
        });
    }

    $(document).ready(function() {
        $('.update_photo').click(function() {

            var id = $(this).attr('id').replace('update_photo_', '');
            console.log(id);
            removeError();
            var newValue = $('#photo_id_' + id).val();
            var postVal = {
                high_photo: newValue,
                id: id
            };

            var url = "<?= $this->popUrl('usermng/change_hphoto') ?>";
            ajaxSave(url, postVal, '照片已经更新', $(this).attr('id'), function() {
                var tdId = 'img_td_' + id;
                if (newValue !== '') {
                    $('#' + tdId).html("<img src='/images/thumbnail/" + newValue + "'>");
                }
                else {
                    $('#' + tdId).html();
                }
            });
            return false;
        });
    });
</script>
<div id="main_message"></div>
<h3>用户列表</h3>

<div>
    <table>
        <thead>
            <tr>
                <th>姓名</th>
                <th>邮件</th>

                <th>用户类型</th>
                <th>操作</th>
                <th>高中照片</th>
                <th>高中照片 ID</th>
                <th>更新高中照片</th>
            </tr>
        </thead>
        <tbody>
            <? foreach ($this->users as $ind => $one): ?>
                <tr <? if ($ind % 2 === 0): ?>class='even_line'<? else: ?>class='odd_line'<? endif; ?>>
                    <td><?= htmlspecialchars($one['name'], ENT_QUOTES, "UTF-8") ?></td>
                    <td><?= htmlspecialchars($one['email'], ENT_QUOTES, "UTF-8") ?></td>
                    <td><?= htmlspecialchars($this->types[intval($one['user_type_id'])], ENT_QUOTES, "UTF-8") ?></td>
                    <td><a href='/usermng/edit?id=<?= $one['id'] ?>'>编辑</a></td>
                    <td id='img_td_<?= $one['id'] ?>'><? if (!empty($this->high_school_photos[$one['id']])): ?><img src='/images/thumbnail/<?= $this->high_school_photos[$one['id']] ?>'><? endif; ?></td>
                    <td><input type="text" value='<? if (!empty($this->high_school_photos[$one['id']])): ?><?= $this->high_school_photos[$one['id']] ?><? endif; ?>' id='photo_id_<?= $one['id'] ?>'></td>
                    <td><button class='update_photo' id='update_photo_<?= $one['id'] ?>'>更新照片</button></td>
                </tr>
            <? endforeach; ?>
        </tbody>
    </table>
</div>
