<div>
    <h3>Teacher Menu:</h3>
</div>


<div class='menu'>

    <a href="<?= $this->popUrl('admin_question/index'); ?>">Question Manager</a>

</div>


<? if($this->teacher['amdin_type']==1):?>
<div class='menu'>
    <a href="<?= $this->popUrl('teacher_mng/index'); ?>">Manager Teacher Account</a>

</div>


<?endif;?>


<div class='menu'>

    <a href="<?= $this->popUrl(''); ?>">Main Page</a>

</div>
