<script type="text/javascript" >
    $(document).ready(function() {
        $('#question_area').load('<?=$this->popUrl("exame_one_by_one/one_question")?>');
        $("#sub_bt").click(function () {
            $.ajax({
                type: "POST",
                url: "<?=$this->popUrl("exame_one_by_one/submit")?>",
                data: $("#question_form").serialize(), // serializes the form's elements.
                success: function(data)
                {
                    if(data==="next"){
                        $('#question_area').load('<?=$this->popUrl("exame_one_by_one/one_question")?>');
                    }
                    else if(data=="finish"){
                        window.location.href = "<?=$this->popUrl("exame_one_by_one/finish")?>";
                    }
                    else{
                        alert("Unknow command:"+data); // show response from the php script.
                    }

                }
            });

        });
    });
</script>

<style>
    #parent:{
        padding-bottom: 10px;
        padding-left: 10px;
        padding-right: 10px;
        padding-top: 10px;

    }
</style>

<div id="parent" >

    <div id="question_area">

    </div>
    <div>
        <button id="sub_bt">Submit</button>
    </div>
</div>
